In [14]:
liste = ["a","b, c", "d", "e"]
x=liste[0:]
print(x)

['a', 'b, c', 'd', 'e']


In [ ]:
saldo = 20000
spare = 2000
rente = 1.03
vf=1+rente/100
for i in range(1, 12):
    saldo = (saldo+spare)*vf
  
print(saldo)

: 

In [15]:
liste1=["a","b","c","d","e"]
liste2=["f","g","h","i","j"]
liste3=liste1+liste2
print(liste3)

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']


In [ ]:
liste1=["a","b","c","d","e"]
liste2=["f","g","h","i","j"]
liste3=liste1+liste2
print(liste3)


TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [17]:
#oppgave 28
liste=[1,2,3,4,5,6,7,8,9,10]
print(liste[0:-1])

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
import math
a=input("Skriv inn et tall: ")
a=int(a)
if a<0:
    print("Tallet er imaginært")
else:
    print (math.sqrt(a))

3.7416573867739413


In [46]:

import numpy as np

verdier = np.linspace(3, 4, 10, endpoint=False)

print(verdier)


[3.  3.1 3.2 3.3 3.4 3.5 3.6 3.7 3.8 3.9]


In [50]:
import numpy as np

verdier = np.full(12,2)
print(verdier)

[2 2 2 2 2 2 2 2 2 2 2 2]


In [64]:
import numpy as np
verdier = np.zeros(12)
verdier.fill(2)
print(verdier)

[2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]


In [70]:
import numpy as np
verdier = np.linspace(2, 2, 12)
print(verdier)

[2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
